/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-11-25 07:18:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentInfoManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>学生信息管理</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jquery-easyui-1.3.3/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jquery-easyui-1.3.3/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-easyui-1.3.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-easyui-1.3.3/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar url;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchStudent(){\r\n");
      out.write("\t\t$('#dg').datagrid('load',{\r\n");
      out.write("\t\t\tstuNo:$('#s_stuNo').val(),\r\n");
      out.write("\t\t\tstuName:$('#s_stuName').val(),\r\n");
      out.write("\t\t\tsex:$('#s_sex').combobox(\"getValue\"),\r\n");
      out.write("\t\t\tgradeId:$('#s_gradeId').combobox(\"getValue\"),\r\n");
      out.write("\t\t\tstuDesc:$('#s_stuDesc').val(),\r\n");
      out.write("\t\t\tstuConsp:$('#s_stuConsp').val(),\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteStudent(){\r\n");
      out.write("\t\tvar selectedRows=$(\"#dg\").datagrid('getSelections');\r\n");
      out.write("\t\tif(selectedRows.length==0){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择要删除的数据！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar strIds=[];\r\n");
      out.write("\t\tfor(var i=0;i<selectedRows.length;i++){\r\n");
      out.write("\t\t\tstrIds.push(selectedRows[i].stuId);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar ids=strIds.join(\",\");\r\n");
      out.write("\t\t$.messager.confirm(\"系统提示\",\"您确认要删掉这<font color=red>\"+selectedRows.length+\"</font>条数据吗？\",function(r){\r\n");
      out.write("\t\t\tif(r){\r\n");
      out.write("\t\t\t\t$.post(\"studentDelete\",{delIds:ids},function(result){\r\n");
      out.write("\t\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"您已成功删除<font color=red>\"+result.delNums+\"</font>条数据\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"系统提示\",\"删除失败\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\"json\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openStudentAddDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"添加学生信息\");\r\n");
      out.write("\t\turl=\"studentSave\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveStudent(){\r\n");
      out.write("\t\t$(\"#fm\").form(\"submit\",{\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\treturn $(this).form(\"validate\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tif(result.errorMsg){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",result.errorMsg);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"系统提示\",\"保存成功\");\r\n");
      out.write("\t\t\t\t\tresetValue();\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$(\"#dg\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction resetValue(){\r\n");
      out.write("\t\t$(\"#stuNo\").val(\"\");\r\n");
      out.write("\t\t$(\"#stuName\").val(\"\");\r\n");
      out.write("\t\t$(\"#sex\").combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#birthday\").datebox(\"setValue\",\"\");\r\n");
      out.write("\t\t$(\"#gradeId\").val(\"\");\r\n");
      out.write("\t\t$(\"#stuDesc\").val(\"\");\r\n");
      out.write("\t\t$(\"#stuConsp\").val(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closeStudentDialog(){\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\tresetValue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openStudentModifyDialog(){\r\n");
      out.write("\t\tvar selectedRows=$(\"#dg\").datagrid('getSelections');\r\n");
      out.write("\t\tif(selectedRows.length!=1){\r\n");
      out.write("\t\t\t$.messager.alert(\"系统提示\",\"请选择一条要编辑的数据！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row=selectedRows[0];\r\n");
      out.write("\t\t$(\"#dlg\").dialog(\"open\").dialog(\"setTitle\",\"编辑学生信息\");\r\n");
      out.write("\t\t$(\"#fm\").form(\"load\",row);\r\n");
      out.write("\t\turl=\"studentSave?stuId=\"+row.stuId;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin:&px;\">\r\n");
      out.write("\t<table id=\"dg\" title=\"学生信息\" class=\"easyui-datagrid\" fitColumns=\"true\"\r\n");
      out.write("\t pagination=\"true\" rownumbers=\"true\" url=\"studentList\" fit=\"true\" toolbar=\"#tb\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"cb\" checkbox=\"true\"></th>\r\n");
      out.write("\t\t\t\t<th field=\"stuId\" width=\"5\" align=\"center\">编号</th>\r\n");
      out.write("\t\t\t\t<th field=\"stuNo\" width=\"10\" align=\"center\">学号</th>\r\n");
      out.write("\t\t\t\t<th field=\"stuName\" width=\"10\" align=\"center\">姓名</th>\r\n");
      out.write("\t\t\t\t<th field=\"sex\" width=\"5\" align=\"center\">性别</th>\r\n");
      out.write("\t\t\t\t<th field=\"birthday\" width=\"20\" align=\"center\">生日</th>\r\n");
      out.write("\t\t\t\t<th field=\"gradeId\" width=\"20\" align=\"center\" hidden=\"true\">班级ID</th>\r\n");
      out.write("\t\t\t\t<th field=\"gradeName\" width=\"20\" align=\"center\">班级名称</th>\r\n");
      out.write("\t\t\t\t<th field=\"stuDesc\" width=\"30\" align=\"center\">学生表现</th>\r\n");
      out.write("\t\t\t\t<th field=\"stuConsp\" width=\"20\" align=\"center\">学生月消费</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"tb\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"javascript:openStudentAddDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">添加</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:openStudentModifyDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">修改</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:deleteStudent()\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">删除</a>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>&nbsp;学号:&nbsp;<input type=\"text\" name=\"s_stuNo\" id=\"s_stuNo\" size=\"10\">\r\n");
      out.write("\t\t&nbsp;姓名:&nbsp;<input type=\"text\" name=\"s_stuName\" id=\"s_stuName\" size=\"5\">\t\r\n");
      out.write("\t\t&nbsp;性别:&nbsp;<select class=\"easyui-combobox\" id=\"s_sex\" name=\"s_sex\" editable=\"false\" panelHeight=\"auto\">\r\n");
      out.write("\t\t\t<option value=\"\">请选择...</option>\r\n");
      out.write("\t\t\t<option value=\"男\">男</option>\r\n");
      out.write("\t\t\t<option value=\"女\">女</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t&nbsp;班级名称:&nbsp;<input class=\"easyui-combobox\" name=\"s_gradeId\" id=\"s_gradeId\" size=\"5\" editable=\"false\" panelHeight=\"auto\" data-options=\"valueField:'id',textField:'gradeName',url:'gradeComboList'\">\t\r\n");
      out.write("\t\t&nbsp;学生表现:&nbsp;<input type=\"text\" name=\"s_stuDesc\" id=\"s_stuDesc\" size=\"5\">\r\n");
      out.write("\t\t&nbsp;月消费:&nbsp;<input type=\"text\" name=\"s_stuConsp\" id=\"s_stuConsp\" size=\"5\">\t\t\t\t\t\r\n");
      out.write("\t\t<a href=\"javascript:searchStudent()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">搜索</a>\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width: 570px;height: 350px;padding:10px 20px\"\r\n");
      out.write("\t\tclosed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\">\r\n");
      out.write("\t\t<table cellspacing=\"&px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>学号:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"stuNo\" id=\"stuNo\" class=\"easyui-validatebox\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>姓名:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"stuName\" id=\"stuName\" class=\"easyui-validatebox\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>性别:</td>\r\n");
      out.write("\t\t\t\t<td><select class=\"easyui-combobox\" id=\"sex\" name=\"sex\" editable=\"false\" panelHeight=\"auto\" style=\"width: 153px\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">请选择...</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"男\">男</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"女\">女</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td>生日:</td>\r\n");
      out.write("\t\t\t\t<td><input class=\"easyui-datebox\" name=\"birthday\" id=\"birthday\" editable=\"false\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>班级名称:</td>\r\n");
      out.write("\t\t\t\t<td><input class=\"easyui-combobox\" name=\"gradeId\" id=\"gradeId\"  editable=\"false\" panelHeight=\"auto\" data-options=\"valueField:'id',textField:'gradeName',url:'gradeComboList'\"></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td>学生表现:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"stuDesc\" id=\"stuDesc\" class=\"easyui-validatebox\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td valign=\"top\">月消费:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"stuConsp\" id=\"stuConsp\" class=\"easyui-validatebox\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:saveStudent()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:closeStudentDialog()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">关闭</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
